## welcome_message.py


def welcome_user():
    print("Welcome to the rainwater quality checker! IMPORTANT: THIS ADVICE SHOULDN'T BE TAKEN VERY SERIOUSLY, THEY ARE ONLY GUESSTIMATES, " \
"ALWAYS DO YOUR RESEARCH BEFORE USING RAINWATER FOR CLEANING OR CONSUMPTION! THIS PROGRAM ALSO ACCESSES YOUR DEVICE'S IP ADDRESS TO LOCATE YOUR CITY, BUT DOESN'T UPLOAD OR STORE THEM")